---
title: "Week 7 Demonstration"
format: html
editor: visual
---

## Set up

```{r}
#| message: FALSE
library(fpp3)
library(tidyverse)
library(slider)
library(gridExtra)
```

## 1. ACVF, ACF, and stationarity

Consider the time series defined as $$
X_t = U_1 \sin(2\pi \omega t) + U_2\cos(2\pi\omega t),
$$ where $U_1$ and $U_2$ are independent random variables with zero mean and variance 1.

a.  Compute the ACVF of $(X_t)$.
b.  Is $(X_t)$ weakly stationary?
c.  Is $(X_t)$ strictly stationary? If not, what conditions can we put on $U_1$ and $U_2$ to make it stationary?

## 2. ACF vs sample ACF

Consider the linear trend model $$
X_t = \beta_0 + \beta_1 t + W_t.
$$

a.  Compute the ACF of $(X_t)$.
b.  Simulate a time series drawn from this model and plot its sample ACF.
c.  Why does the sample ACF not look like the population ACF function?
d.  Why does the asymptotic normality theorem for the ACF not apply?

## 3. Prediction interval widths

Consider the linear trend method, the drift method, and the seasonal naive method.

a\. What is the formula for the width of their prediction intervals as a function of the forecast horizon $h$?

b\. Use all 3 methods to forecast for `aus_arrivals` and verify this is the case.

## 4. Gaussian conditional distribution in 2D

Let $(X_1,X_2)$ be a 2D Gaussian random vector with mean $\mu = (1, 1)$ and covariance matrix

$$
\Sigma = \begin{bmatrix} 2  & 2\rho \\ 2\rho & 2\end{bmatrix}
$$

a\. From first principles, derive the conditional distribution of $X_2$ given $X_1=x_1$.

b\. How does the distribution change as $\rho$ changes? How about as $x_1$ changes?

c\. Make a scatter plot of the joint distribution of $(X_1,X_2)$ for $\rho = 0.1$ and for $\rho = 0.9$ . Does this agree with your answer from (b) and (c)?

## 5. Forecasting

Let $(X_t)$ be a zero mean stationary process with $\rho_X(h) \neq 0$ for some $h$

a.  Find $A$ minimizing $\mathbb{E}\lbrace (X_{n+h} - A X_n)^2 \rbrace$.
b.  Use this to make a forecast for $X_{n+h}$ given $X_1,\ldots,X_n$.
c.  What is the MSE for the forecast?
d.  What is the consequence of this for ACF values?
